const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const api = require('../dist');

const temporaryRoot = path.resolve('./tests/.tmp');
fs.mkdirSync(temporaryRoot, { recursive: true });
const projectRoot = fs.mkdtempSync(path.join(temporaryRoot, 'agent-adapters-'));
const claudeEntryPath = path.join(projectRoot, 'CLAUDE.md');
const copilotEntryPath = path.join(projectRoot, '.github/copilot-instructions.md');
fs.writeFileSync(claudeEntryPath, 'user-managed Claude instructions', 'utf8');
fs.mkdirSync(path.dirname(copilotEntryPath), { recursive: true });
fs.writeFileSync(copilotEntryPath, 'user-managed Copilot instructions', 'utf8');
const registry = api.readRegistry('./registry');

assert.deepEqual(registry.issues, []);
assert.deepEqual(api.supportedAgentIds, [
  'codex',
  'claude-code',
  'cursor',
  'github-copilot',
]);
assert.equal(api.getAgentAdapter('claude').id, 'claude-code');
assert.equal(api.getAgentAdapter('copilot').id, 'github-copilot');

const expectedIncluded = [
  'company.communication',
  'company.dependency-changes',
  'company.common',
  'company.git-workspace-safety',
  'company.verification',
  'company.coding-standards',
  'frontend.typescript',
  'frontend.common',
];
const expectedAvailable = [
  'company.youtrack-development-backlog-task',
  'frontend.code-review',
  'frontend.generated-openapi-status-noise',
];
const cases = [
  {
    agent: 'claude-code',
    requiredRule: '.claude/rules/agentsync/required.md',
    skill: '.claude/skills/agentsync-frontend-code-review/SKILL.md',
    rulePattern: /<!-- Generated by ai-skills/,
  },
  {
    agent: 'cursor',
    requiredRule: '.cursor/rules/agentsync-required.mdc',
    skill: '.cursor/skills/agentsync-frontend-code-review/SKILL.md',
    rulePattern: /alwaysApply: true/,
  },
  {
    agent: 'github-copilot',
    requiredRule: '.github/instructions/agentsync-required.instructions.md',
    skill: '.github/skills/agentsync-frontend-code-review/SKILL.md',
    rulePattern: /applyTo: "\*\*"/,
  },
];

for (const testCase of cases) {
  const adapter = api.getAgentAdapter(testCase.agent);
  const resolveResult = api.resolveSkills(registry.skills, {
    project: 'statistics',
    agent: testCase.agent,
    technologies: ['typescript'],
  });
  const files = adapter.generateFiles(resolveResult);
  const byPath = new Map(files.map((file) => [file.relativePath, file.content]));

  assert.deepEqual(resolveResult.included.map((skill) => skill.id), expectedIncluded);
  assert.deepEqual(resolveResult.available.map((skill) => skill.id), expectedAvailable);
  assert.equal(resolveResult.warnings.length, 0);
  assert.ok(byPath.has(testCase.requiredRule));
  assert.ok(byPath.has(testCase.skill));
  assert.match(byPath.get(testCase.requiredRule), testCase.rulePattern);
  assert.match(
    byPath.get(testCase.skill),
    /^---\nname: agentsync-frontend-code-review\ndescription:/,
  );

  const index = JSON.parse(byPath.get(adapter.skillIndexPath));
  assert.equal(index.agent, testCase.agent);
  assert.equal(index.generatedSkillFiles.length, 7);
  assert.equal(
    index.available.find((skill) => skill.id === 'frontend.code-review').generatedEntrypoint,
    testCase.skill,
  );

  adapter.writeFiles(projectRoot, resolveResult);
  assert.ok(fs.existsSync(path.join(projectRoot, testCase.requiredRule)));
  assert.ok(fs.existsSync(path.join(projectRoot, testCase.skill)));

  const emptyResolveResult = {
    ...resolveResult,
    included: [],
    available: [],
    manifest: {
      ...resolveResult.manifest,
      included: [],
      available: [],
      estimatedTokens: 0,
    },
  };
  const emptyFiles = adapter.generateFiles(emptyResolveResult);
  assert.equal(emptyFiles.some((file) => file.relativePath === testCase.skill), false);

  adapter.writeFiles(projectRoot, emptyResolveResult);

  assert.ok(fs.existsSync(path.join(projectRoot, testCase.requiredRule)));
}

assert.equal(fs.readFileSync(claudeEntryPath, 'utf8'), 'user-managed Claude instructions');
assert.equal(fs.readFileSync(copilotEntryPath, 'utf8'), 'user-managed Copilot instructions');

console.log('agent adapter tests passed');
