const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const api = require('../dist');
const { setupTestProject } = require('./helpers/test-project');

const projectRoot = setupTestProject();
const registry = api.readRegistry('./registry');
const configResult = api.readProjectConfig(path.join(projectRoot, '.ai-skills.json'));

assert.deepEqual(registry.issues, []);
assert.deepEqual(configResult.issues, []);

const config = configResult.config;
assert.deepEqual(api.codexDefaultOutput, {
  entry: 'AGENTS.md',
  generatedDir: '.agents/generated',
});
assert.deepEqual(
  api.normalizeProjectConfig({
    project: 'statistics',
    repository: 'statistics-ui',
    agents: ['codex'],
    registry: './registry',
    output: {
      codex: {
        entry: 'AGENTS.md',
        generatedDir: '.agents/generated',
      },
    },
    budgets: {
      bootstrap: 1500,
    },
  }).issues.map((issue) => issue.code),
  [
    'unknown_project_config_field',
    'unknown_project_config_field',
    'unknown_project_config_field',
  ],
);

const resolveResult = api.resolveSkills(registry.skills, {
  project: config.project,
  agent: 'codex',
  technologies: ['typescript'],
});

const generated = api.generateCodexFiles({
  resolveResult,
  output: api.codexDefaultOutput,
});

assert.deepEqual(
  generated.files.map((file) => file.relativePath),
  [
    'AGENTS.md',
    '.agents/generated/active-rules.md',
    '.agents/generated/rule-scope.md',
    '.agents/generated/skill-index.json',
    '.agents/generated/rules/required.md',
    '.agents/generated/rules/communication.md',
    '.agents/generated/rules/dependencies.md',
    '.agents/generated/rules/frontend.md',
    '.agents/generated/rules/general.md',
    '.agents/generated/rules/git.md',
    '.agents/generated/rules/typescript.md',
    '.agents/generated/rules/verification.md',
    '.agents/generated/skills/frontend-code-review/SKILL.md',
    '.agents/generated/skills/generated-openapi-status-noise/references/EXAMPLES.md',
    '.agents/generated/skills/generated-openapi-status-noise/references/STRUCTURE.md',
    '.agents/generated/skills/generated-openapi-status-noise/SKILL.md',
    '.agents/generated/skills/youtrack-development-backlog-task/references/EXAMPLES.md',
    '.agents/generated/skills/youtrack-development-backlog-task/references/STRUCTURE.md',
    '.agents/generated/skills/youtrack-development-backlog-task/SKILL.md',
  ],
);
assert.match(generated.entry.content, /Инструкции для AI-агента/);
assert.match(
  generated.entry.content,
  /\[\.agents\/generated\/active-rules\.md\]\(\.agents\/generated\/active-rules\.md\)/,
);
assert.match(
  generated.entry.content,
  /\[\.agents\/generated\/rule-scope\.md\]\(\.agents\/generated\/rule-scope\.md\)/,
);
assert.match(
  generated.entry.content,
  /\[\.agents\/generated\/skill-index\.json\]\(\.agents\/generated\/skill-index\.json\)/,
);
assert.match(generated.activeRules.content, /Generated by ai-skills/);
assert.match(generated.activeRules.content, /# Active AI Rules/);
assert.match(generated.ruleScope.content, /# Rule Scope/);
assert.match(generated.ruleScope.content, /Any task/);
assert.ok(
  generated.ruleFiles.some(
    (file) => file.relativePath === '.agents/generated/rules/required.md',
  ),
);
assert.ok(
  generated.ruleFiles.some(
    (file) => file.relativePath === '.agents/generated/rules/frontend.md',
  ),
);

const skillIndex = JSON.parse(generated.skillIndex.content);
assert.deepEqual(
  skillIndex.included.map((skill) => skill.id),
  [
    'company.communication',
    'company.dependency-changes',
    'company.common',
    'company.git-workspace-safety',
    'company.verification',
    'company.coding-standards',
    'frontend.typescript',
    'frontend.common',
  ],
);
assert.deepEqual(skillIndex.available.map((skill) => skill.id), [
  'company.youtrack-development-backlog-task',
  'frontend.code-review',
  'frontend.generated-openapi-status-noise',
]);
const codeReviewSkill = skillIndex.available.find(
  (skill) => skill.id === 'frontend.code-review',
);
assert.equal(codeReviewSkill.kind, 'skill');
assert.equal(codeReviewSkill.entrypoint, 'skills/frontend-code-review/material.md');
assert.equal(
  codeReviewSkill.generatedEntrypoint,
  '.agents/generated/skills/frontend-code-review/SKILL.md',
);
assert.deepEqual(skillIndex.generatedSkillFiles, [
  '.agents/generated/skills/frontend-code-review/SKILL.md',
  '.agents/generated/skills/generated-openapi-status-noise/references/EXAMPLES.md',
  '.agents/generated/skills/generated-openapi-status-noise/references/STRUCTURE.md',
  '.agents/generated/skills/generated-openapi-status-noise/SKILL.md',
  '.agents/generated/skills/youtrack-development-backlog-task/references/EXAMPLES.md',
  '.agents/generated/skills/youtrack-development-backlog-task/references/STRUCTURE.md',
  '.agents/generated/skills/youtrack-development-backlog-task/SKILL.md',
]);

api.writeCodexFiles({
  projectRoot,
  resolveResult,
  output: api.codexDefaultOutput,
});

assert.ok(fs.existsSync(path.join(projectRoot, 'AGENTS.md')));
assert.ok(fs.existsSync(path.join(projectRoot, '.agents/generated/active-rules.md')));
assert.ok(fs.existsSync(path.join(projectRoot, '.agents/generated/rule-scope.md')));
assert.ok(fs.existsSync(path.join(projectRoot, '.agents/generated/skill-index.json')));
assert.ok(fs.existsSync(path.join(projectRoot, '.agents/generated/rules/required.md')));
assert.ok(fs.existsSync(path.join(projectRoot, '.agents/generated/skills/frontend-code-review/SKILL.md')));
assert.ok(fs.existsSync(path.join(projectRoot, '.agents/generated/skills/generated-openapi-status-noise/SKILL.md')));

assert.throws(() => {
  api.writeCodexFiles({
    projectRoot,
    resolveResult,
    output: {
      entry: '../AGENTS.md',
      generatedDir: '.agents/generated',
    },
  });
}, /escapes project root/);

console.log('codex adapter tests passed');
