import { join } from 'node:path';
import {
  AvailableSkill,
  ResolveResult,
  ResolvedSkill,
} from '../../composer/types';
import {
  CodexAdapterInput,
  CodexGeneratedFiles,
  GeneratedFile,
} from './types';

const activeRulesFileName = 'active-rules.md';
const ruleScopeFileName = 'rule-scope.md';
const skillIndexFileName = 'skill-index.json';
const rulesDirName = 'rules';
const skillsDirName = 'skills';
const bootstrapRequiredCategories = [
  'communication',
  'git',
  'general',
  'verification',
  'dependencies',
  'security',
];

const categoryTitles: Record<string, string> = {
  general: 'Общие правила',
  communication: 'Коммуникация',
  git: 'Git и рабочая директория',
  verification: 'Проверки',
  dependencies: 'Зависимости',
  frontend: 'Frontend',
  bff: 'BFF',
  backend: 'Backend',
  typescript: 'TypeScript',
  html: 'HTML templates',
  scss: 'SCSS',
  architecture: 'Архитектура',
  security: 'Безопасность',
};

export function generateCodexFiles(input: CodexAdapterInput): CodexGeneratedFiles {
  const activeRulesPath = normalizeRelativePath(join(input.output.generatedDir, activeRulesFileName));
  const ruleScopePath = normalizeRelativePath(join(input.output.generatedDir, ruleScopeFileName));
  const skillIndexPath = normalizeRelativePath(join(input.output.generatedDir, skillIndexFileName));
  const ruleFiles = createRuleFiles(input.resolveResult, input.output.generatedDir);
  const skillFiles = createSkillFiles(input.resolveResult, input.output.generatedDir);

  const entry: GeneratedFile = {
    relativePath: normalizeRelativePath(input.output.entry),
    content: renderAgentsMd(activeRulesPath, ruleScopePath, skillIndexPath),
  };
  const activeRules: GeneratedFile = {
    relativePath: activeRulesPath,
    content: renderActiveRules(input.resolveResult, ruleScopeFileName, ruleFiles),
  };
  const ruleScope: GeneratedFile = {
    relativePath: ruleScopePath,
    content: renderRuleScope(input.resolveResult, ruleFiles),
  };
  const skillIndex: GeneratedFile = {
    relativePath: skillIndexPath,
    content: renderSkillIndex(input.resolveResult, ruleFiles, skillFiles),
  };

  return {
    entry,
    activeRules,
    ruleScope,
    skillIndex,
    ruleFiles,
    skillFiles,
    files: [entry, activeRules, ruleScope, skillIndex, ...ruleFiles, ...skillFiles],
  };
}

export function renderAgentsMd(
  activeRulesPath: string,
  ruleScopePath: string,
  skillIndexPath: string,
): string {
  return normalizeNewlines(`# Инструкции для AI-агента

В этом репозитории используются централизованные AI-скиллы.

Всегда сначала прочитай bootstrap-правила:
- [${activeRulesPath}](${activeRulesPath})

Для выбора правил под конкретную задачу используй карту применимости:
- [${ruleScopePath}](${ruleScopePath})

Индекс всех сгенерированных правил и справочных материалов:
- [${skillIndexPath}](${skillIndexPath})

Generated local skills:
- [.agents/generated/skills](.agents/generated/skills)

Файлы сгенерированы автоматически. Не редактируй их вручную.
Для обновления запусти \`ai-skills sync\`.
`);
}

export function renderActiveRules(
  resolveResult: ResolveResult,
  ruleScopePath: string,
  ruleFiles: GeneratedFile[],
): string {
  const manifest = resolveResult.manifest;
  const includedSkills = manifest.included
    .map((skill) => `- ${skill.id}@${skill.version}`)
    .join('\n');
  const taskTypeLine = manifest.taskType ? `Task type: ${manifest.taskType}\n` : '';
  const availableRuleSets = ruleFiles
    .map((file) => {
      const title = getRuleFileTitle(file.relativePath);
      const link = getGeneratedRelativeLink(file.relativePath);
      return `- [${title}](${link})`;
    })
    .join('\n');

  return normalizeNewlines(`<!--
Generated by ai-skills
Project: ${manifest.project}
Agent: ${manifest.agent}
${taskTypeLine}Estimated tokens: ${manifest.estimatedTokens}
Included rules:
${includedSkills || '- none'}
Checksum: ${manifest.checksum}
-->

# Active AI Rules

Этот файл является коротким bootstrap-слоем. Не пытайся применить все
правила сразу: сначала определи область задачи, затем открой релевантные
разделы из карты применимости.

## Доступные активные наборы правил

${availableRuleSets || '- Нет активных наборов правил для текущего контекста.'}

## Как выбирать правила

1. Определи область задачи по изменяемым путям, технологиям и типу задачи.
2. Открой карту применимости: [${ruleScopePath}](${ruleScopePath}).
3. Примени обязательные правила и только релевантные category rules.
4. Не усложняй маленькую правку нерелевантными правилами.
5. Если задача затрагивает несколько областей, применяй правила всех затронутых областей.
`);
}

export function renderRuleScope(
  resolveResult: ResolveResult,
  ruleFiles: GeneratedFile[],
): string {
  const categoryLinks = createCategoryLinks(ruleFiles);
  const lines = [
    '# Rule Scope',
    '',
    'Используй эту карту, чтобы быстро выбрать релевантные правила для задачи.',
    '',
    '## Any task',
    '',
    '- Всегда учитывай обязательные правила: [required](rules/required.md).',
    categoryLinks.git ? `- Для работы с Git и рабочей директорией: ${categoryLinks.git}.` : '',
    categoryLinks.communication ? `- Для коммуникации с пользователем: ${categoryLinks.communication}.` : '',
    categoryLinks.verification ? `- Для выбора проверок после изменений: ${categoryLinks.verification}.` : '',
    '',
    '## apps/front',
    '',
    categoryLinks.frontend ? `- Frontend rules: ${categoryLinks.frontend}.` : '',
    categoryLinks.architecture ? `- Architecture/layout rules: ${categoryLinks.architecture}.` : '',
    categoryLinks.typescript ? `- TypeScript rules: ${categoryLinks.typescript}.` : '',
    categoryLinks.html ? `- HTML/template rules: ${categoryLinks.html}.` : '',
    categoryLinks.scss ? `- SCSS rules: ${categoryLinks.scss}.` : '',
    '',
    '## apps/bff',
    '',
    categoryLinks.bff ? `- BFF/NestJS rules: ${categoryLinks.bff}.` : '',
    categoryLinks.security ? `- Security/secret rules: ${categoryLinks.security}.` : '',
    '',
    '## BFF Swagger changes',
    '',
    categoryLinks.bff ? `- Используй BFF rules: ${categoryLinks.bff}.` : '',
    '- Не запускай frontend API generation после изменения BFF Swagger contracts.',
    '- В финальном отчете укажи, что BFF готов для frontend generation.',
    '',
    '## Git branch/commit tasks',
    '',
    categoryLinks.git ? `- Для операций с ветками и commit-сообщениями правила из ${categoryLinks.git} обязательны.` : '',
    '',
    '## Dependencies',
    '',
    categoryLinks.dependencies ? `- Используй dependency rules: ${categoryLinks.dependencies}.` : '',
    '',
    '## Included rules',
    '',
    ...resolveResult.included.map((skill) => (
      `- ${skill.id}@${skill.version} (${skill.category}, ${skill.severity})`
    )),
  ];

  return normalizeNewlines(lines.join('\n').replace(/\n{3,}/g, '\n\n'));
}

export function renderSkillIndex(
  resolveResult: ResolveResult,
  ruleFiles: GeneratedFile[],
  skillFiles: GeneratedFile[] = [],
): string {
  return `${JSON.stringify(
    {
      agent: resolveResult.manifest.agent,
      project: resolveResult.manifest.project,
      taskType: resolveResult.manifest.taskType,
      checksum: resolveResult.manifest.checksum,
      estimatedTokens: resolveResult.manifest.estimatedTokens,
      generatedFiles: ruleFiles.map((file) => file.relativePath),
      generatedSkillFiles: skillFiles.map((file) => file.relativePath),
      included: resolveResult.included.map((skill) => ({
        id: skill.id,
        kind: skill.kind,
        title: skill.title,
        summary: skill.summary,
        version: skill.version,
        scope: skill.scope,
        category: skill.category,
        severity: skill.severity,
        loadMode: skill.loadMode,
        sourceFile: skill.sourceFile,
        estimatedTokens: skill.estimatedTokens,
      })),
      available: resolveResult.available.map((skill) => ({
        id: skill.id,
        kind: skill.kind,
        title: skill.title,
        summary: skill.summary,
        version: skill.version,
        scope: skill.scope,
        category: skill.category,
        severity: skill.severity,
        loadMode: skill.loadMode,
        sourceFile: skill.sourceFile,
        entrypoint: skill.entrypoint,
        resources: skill.resources,
        generatedEntrypoint: getGeneratedSkillEntrypoint(skillFiles, skill),
      })),
      skipped: resolveResult.skipped.map((skill) => ({
        id: skill.id,
        title: skill.title,
        reason: skill.reason,
      })),
      warnings: resolveResult.warnings,
    },
    null,
    2,
  )}\n`;
}

function createSkillFiles(
  resolveResult: ResolveResult,
  generatedDir: string,
): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  for (const skill of resolveResult.available) {
    if (skill.kind !== 'skill') {
      continue;
    }

    const skillDir = getSkillOutputDirName(skill);

    if (!skillDir) {
      continue;
    }

    const outputDir = normalizeRelativePath(join(generatedDir, skillsDirName, skillDir));
    files.push({
      relativePath: normalizeRelativePath(join(outputDir, 'SKILL.md')),
      content: renderCodexSkill(skill, skillDir),
    });

    for (const resourceFile of skill.resourceFiles || []) {
      if (!isSafeSkillRelativePath(resourceFile.relativePath)) {
        continue;
      }

      files.push({
        relativePath: normalizeRelativePath(join(outputDir, resourceFile.relativePath)),
        content: normalizeNewlines(resourceFile.content),
      });
    }
  }

  return files.sort((left, right) => left.relativePath.localeCompare(right.relativePath));
}

function renderCodexSkill(skill: AvailableSkill, name: string): string {
  return normalizeNewlines(`---
name: ${name}
description: ${JSON.stringify(skill.summary)}
---

${skill.body.trim()}
`);
}

function getGeneratedSkillEntrypoint(
  skillFiles: GeneratedFile[],
  skill: AvailableSkill,
): string | undefined {
  const skillDir = getSkillOutputDirName(skill);

  if (!skillDir) {
    return undefined;
  }

  const directSuffix = '/skills/' + skillDir + '/SKILL.md';
  const namespacedSuffix = '/skills/agentsync-' + skillDir + '/SKILL.md';

  return skillFiles.find((file) => (
    file.relativePath.endsWith(directSuffix) ||
    file.relativePath.endsWith(namespacedSuffix)
  ))?.relativePath;
}

function getSkillOutputDirName(skill: AvailableSkill): string | undefined {
  const match = skill.entrypoint?.match(/^skills\/(.+)\/material\.md$/);

  if (!match) {
    return undefined;
  }

  return match[1];
}

function isSafeSkillRelativePath(relativePath: string): boolean {
  return (
    normalizeRelativePath(relativePath) === relativePath &&
    relativePath !== '' &&
    !relativePath.startsWith('/') &&
    !relativePath.startsWith('../') &&
    !relativePath.includes('/../')
  );
}

function createRuleFiles(
  resolveResult: ResolveResult,
  generatedDir: string,
): GeneratedFile[] {
  const groups = new Map<string, ResolvedSkill[]>();

  for (const skill of resolveResult.included) {
    const current = groups.get(skill.category) || [];
    current.push(skill);
    groups.set(skill.category, current);
  }

  const requiredSkills = resolveResult.included
    .filter((skill) => (
      skill.severity === 'required' &&
      bootstrapRequiredCategories.includes(skill.category)
    ));
  const files: GeneratedFile[] = [];

  files.push({
    relativePath: normalizeRelativePath(join(generatedDir, rulesDirName, 'required.md')),
    content: renderRuleFile('Обязательные правила', requiredSkills),
  });

  for (const category of Array.from(groups.keys()).sort()) {
    files.push({
      relativePath: normalizeRelativePath(join(generatedDir, rulesDirName, `${category}.md`)),
      content: renderRuleFile(categoryTitles[category] || category, groups.get(category) || []),
    });
  }

  return files;
}

function renderRuleFile(title: string, skills: ResolvedSkill[]): string {
  const sections = skills
    .map((skill) => renderSkillSection(skill))
    .join('\n\n');

  return normalizeNewlines(`# ${title}

${sections || 'Нет правил для этой категории в текущем контексте.'}
`);
}

function renderSkillSection(skill: ResolvedSkill): string {
  return `## ${skill.title}

Metadata: \`${skill.id}@${skill.version}\`, category: \`${skill.category}\`, severity: \`${skill.severity}\`

${skill.body.trim()}`;
}

function createCategoryLinks(ruleFiles: GeneratedFile[]): Record<string, string> {
  const result: Record<string, string> = {};

  for (const file of ruleFiles) {
    const match = file.relativePath.match(/rules\/(.+)\.md$/);

    if (!match) {
      continue;
    }

    const category = match[1];
    result[category] = `[${category}](rules/${category}.md)`;
  }

  return result;
}

function getRuleFileTitle(relativePath: string): string {
  const match = relativePath.match(/rules\/(.+)\.md$/);

  if (!match) {
    return relativePath;
  }

  const category = match[1];

  if (category === 'required') {
    return 'Bootstrap required';
  }

  return categoryTitles[category] || category;
}

function getGeneratedRelativeLink(relativePath: string): string {
  const match = relativePath.match(/\.agents\/generated\/(.+)$/);
  return match ? match[1] : relativePath;
}

function normalizeNewlines(value: string): string {
  return `${value.replace(/\r\n/g, '\n').trim()}\n`;
}

function normalizeRelativePath(value: string): string {
  return value.replace(/\\/g, '/');
}
